Write SOP (resolves #85)
BD2KGenomics/core-operations pull request #86
Opened 2016-10-11 21:11 UTC by jvivian

2016-10-11 21:12 UTC, jvivian commented
@hannes-ucsc — This is just a first stab. I figured I'd let @JakeNarkizian use this as his template for the next production run and he can give me feedback if anything is unclear.

2016-10-12 06:34 UTC, hannes-ucsc requested changes

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +6. Set `~/.profile` options from CGCloud README
Be explicit. No linking or references except for optional steps. This document should be self contained. Be sure to mention `CGCLOUD_KEYPAIRS`.

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> + These steps should only have to be run once. Toil-box images will have to be updated periodically to stay current.
So for readability you should always backquote strings that a user would type into a command line.

So for example:

```
Bash can be started by running the `bash` command.
```

Or in this case:

```
The `toil-box` image will …
```

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> + These steps should only have to be run once. Toil-box images will have to be updated periodically to stay current.
"periodically" is imprecise. When exactly should they update?

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +6. Set `~/.profile` options from CGCloud README
```
The following steps are provided for referecnce but it is recommended to read the source documentation to gain full understanding on how to use CGCloud.
```

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +Comprehensive help is found at: https://github.com/BD2KGenomics/cgcloud .
Markdown can do hyperlinks.

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +1. `cgcloud ssh -c example toil-leader`
Mention briefly that `-c` is same as `--cluster-name`

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +10. `screen -S example-run`
10 is duplicated

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +5. Run the binary for the pipeline, example: `toil-rnaseq` for the RNA-seq CGL pipeline.
`toil-rnaseq`  is not a binary

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +5. Run the binary for the pipeline, example: `toil-rnaseq` for the RNA-seq CGL pipeline.
Isn't it "RNASeq"?

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +8. `cgcloud grow-cluster --cluster-name example --spot-auto-zone --spot-bid 1.00 --instance-type c3.8xlarge --num-workers 22 toil`
Add section on choosing spot market price.

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +or Toil itself. Failures generally stem from an issue with the sample -- improperly paired reads, samples too large for
I like your confidence but there is little evidence for the claim in the second sentence.

2016-10-12 06:34 UTC, hannes-ucsc commented on Production_SOP.md
> +This assumption isn't based on hubris, but the fact that the pipeline had a throughput of 99.6% across 20,000 samples.
This sounds arrogant. It was a different version of the pipeline and a different version of Toil. And we had plenty of problems during the run. The fact that Toil+Pipeline were able to run 20k samples with plenty of hand-holding doesn't mean that Joe Shmo should have no problems with their 20 samples.

2016-10-12 17:29 UTC, jvivian commented on Production_SOP.md
> + These steps should only have to be run once. Toil-box images will have to be updated periodically to stay current.
> "periodically" is imprecise. When exactly should they update?

That's a good question, I replaced it with: 

" `toil-box` images will have to be updated following major releases of Toil that contain critical features or bug fixes, or at the direction of the Toil development team."

2016-10-12 17:29 UTC, jvivian commented on Production_SOP.md
> +Comprehensive help is found at: https://github.com/BD2KGenomics/cgcloud .
Corrected.

2016-10-12 17:29 UTC, jvivian commented on Production_SOP.md
> +6. Set `~/.profile` options from CGCloud README
Substituted in your comment, added `~/.profile` options.

2016-10-12 17:30 UTC, jvivian commented on Production_SOP.md
> +1. `cgcloud ssh -c example toil-leader`
I replaced with the full name for clarity.

2016-10-12 17:31 UTC, jvivian commented on Production_SOP.md
> +5. Run the binary for the pipeline, example: `toil-rnaseq` for the RNA-seq CGL pipeline.
/s/binary/entrypoint.

Typically I see [RNA-seq](https://en.wikipedia.org/wiki/RNA-Seq)

2016-10-12 17:31 UTC, jvivian commented on Production_SOP.md
> +8. `cgcloud grow-cluster --cluster-name example --spot-auto-zone --spot-bid 1.00 --instance-type c3.8xlarge --num-workers 22 toil`
Added section.

2016-10-12 17:31 UTC, jvivian commented on Production_SOP.md
> +10. `screen -S example-run`
Corrected.

2016-10-12 17:31 UTC, jvivian commented on Production_SOP.md
> +or Toil itself. Failures generally stem from an issue with the sample -- improperly paired reads, samples too large for
I removed this section completely.

2016-10-12 17:32 UTC, jvivian commented on Production_SOP.md
> +This assumption isn't based on hubris, but the fact that the pipeline had a throughput of 99.6% across 20,000 samples.
I agree, and not appropriate for technical documentation. I just removed this section.

2016-10-18 17:32 UTC, jvivian commented
@hannes-ucsc — Ready for review. I believe @JakeNarkizian plans on running the next production batch, so maybe he can use this SOP for that and provide feedback first.

2016-10-19 07:36 UTC, JakeNarkizian commented
@jvivian I started a production run on monday night already, but I can simulate a production order.

2016-10-26 18:44 UTC, hannes-ucsc approved these changes

2016-10-26 18:45 UTC, merged